"""Turn the summary CSVs into LaTeX tables the report can \\input directly.

Retyping numbers from a CSV into a .tex file by hand is how a report ends up
disagreeing with its own results. This script writes one booktabs table per
(dataset, sweep, metric) into ``report/tables/`` so the report always shows
what the code actually produced; re-running it after new experiments updates
every table at once.

Usage (from ``code/``):

    python make_tables.py                       # all datasets and sweeps
    python make_tables.py --metric rre          # just the RRE tables

Then, in report.tex:

    \\input{tables/orl_contamination_rre.tex}
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

SWEEP_AXIS = {
    'blocksize': ('block_size', r'block edge length $b$'),
    'blockcount': ('n_blocks', r'number of blocks'),
    'contamination': ('fraction', r'fraction of images corrupted'),
}
METRIC_LABEL = {
    'rre': ('RRE', 'lower is better'),
    'accuracy': ('Accuracy', 'higher is better'),
    'nmi': ('NMI', 'higher is better'),
}
DATASET_LABEL = {'orl': 'ORL', 'yaleb': 'Extended YaleB'}


def escape(text):
    """Escape the LaTeX-special characters that occur in algorithm names."""
    return str(text).replace('_', r'\_').replace('&', r'\&')


def build_table(rows, dataset, sweep, metric):
    axis_col, axis_label = SWEEP_AXIS[sweep]
    metric_label, direction = METRIC_LABEL[metric]

    axis_values, algorithms = [], []
    for r in rows:
        value = float(r[axis_col])
        if value not in axis_values:
            axis_values.append(value)
        if r['algorithm'] not in algorithms:
            algorithms.append(r['algorithm'])
    axis_values.sort()

    lookup = {(float(r[axis_col]), r['algorithm']): r for r in rows}

    def fmt(value, alg):
        r = lookup.get((value, alg))
        if r is None:
            return '--'
        mean, std = float(r[f'mean_{metric}']), float(r[f'std_{metric}'])
        if mean != mean:  # NaN
            return '--'
        return f'${mean:.4f} \\pm {std:.4f}$'

    # Bold the best algorithm in each column.
    best = {}
    for value in axis_values:
        scores = {}
        for alg in algorithms:
            r = lookup.get((value, alg))
            if r is None:
                continue
            mean = float(r[f'mean_{metric}'])
            if mean == mean:
                scores[alg] = mean
        if scores:
            best[value] = (min if metric == 'rre' else max)(scores, key=scores.get)

    def axis_fmt(value):
        return f'{value:g}'

    lines = [
        '% generated by code/make_tables.py -- do not edit by hand',
        r'\begin{table}[tbp]',
        r'  \centering',
        f'  \\caption{{{DATASET_LABEL[dataset]}: {metric_label} '
        f'({direction}) against {axis_label}. '
        r'Mean $\pm$ standard deviation over five independent $90\%$ '
        r'subsamples; best per column in bold.}',
        f'  \\label{{tab:{dataset}-{sweep}-{metric}}}',
        r'  \footnotesize',
        r'  \setlength{\tabcolsep}{4pt}',
        r'  \begin{tabular}{l' + 'c' * len(axis_values) + '}',
        r'    \toprule',
        '    Algorithm & '
        + ' & '.join(f'${axis_fmt(v)}$' for v in axis_values) + r' \\',
        r'    \midrule',
    ]
    for alg in algorithms:
        cells = []
        for value in axis_values:
            cell = fmt(value, alg)
            if best.get(value) == alg and cell != '--':
                cell = r'\bm{' + cell.strip('$').join(('$', '$')) + '}'
                cell = cell.replace(r'\bm{$', r'$\bm{').replace(r'$}', r'}$')
            cells.append(cell)
        lines.append(f'    {escape(alg)} & ' + ' & '.join(cells) + r' \\')
    lines += [r'    \bottomrule', r'  \end{tabular}', r'\end{table}', '']
    return '\n'.join(lines)


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--results', default='results')
    p.add_argument('--out', default='../report/tables')
    p.add_argument('--datasets', nargs='+', default=['orl', 'yaleb'])
    p.add_argument('--sweeps', nargs='+', default=list(SWEEP_AXIS))
    p.add_argument('--metric', nargs='+', default=list(METRIC_LABEL))
    args = p.parse_args()

    results, out_dir = Path(args.results), Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = 0

    for dataset in args.datasets:
        for sweep in args.sweeps:
            path = results / f'{dataset}_{sweep}_summary.csv'
            if not path.exists():
                print(f'skip (not found): {path}')
                continue
            with path.open(encoding='utf-8') as f:
                rows = list(csv.DictReader(f))
            for metric in args.metric:
                if f'mean_{metric}' not in rows[0]:
                    continue
                target = out_dir / f'{dataset}_{sweep}_{metric}.tex'
                target.write_text(build_table(rows, dataset, sweep, metric),
                                  encoding='utf-8')
                written += 1
    print(f'wrote {written} LaTeX tables into {out_dir}')


if __name__ == '__main__':
    main()
